//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Inputs/ExitToMenu.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ExitToMenu : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ExitToMenu()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ExitToMenu"",
    ""maps"": [
        {
            ""name"": ""Menu Exit"",
            ""id"": ""3d485f41-bfd5-4cdb-90f2-b0659bddeb87"",
            ""actions"": [
                {
                    ""name"": ""Button"",
                    ""type"": ""Button"",
                    ""id"": ""6bcc0d10-4aba-4bd0-b31b-e7641a567168"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e962b92e-507f-4c3d-9913-272fb1d821f4"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Button"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Menu Exit
        m_MenuExit = asset.FindActionMap("Menu Exit", throwIfNotFound: true);
        m_MenuExit_Button = m_MenuExit.FindAction("Button", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Menu Exit
    private readonly InputActionMap m_MenuExit;
    private IMenuExitActions m_MenuExitActionsCallbackInterface;
    private readonly InputAction m_MenuExit_Button;
    public struct MenuExitActions
    {
        private @ExitToMenu m_Wrapper;
        public MenuExitActions(@ExitToMenu wrapper) { m_Wrapper = wrapper; }
        public InputAction @Button => m_Wrapper.m_MenuExit_Button;
        public InputActionMap Get() { return m_Wrapper.m_MenuExit; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuExitActions set) { return set.Get(); }
        public void SetCallbacks(IMenuExitActions instance)
        {
            if (m_Wrapper.m_MenuExitActionsCallbackInterface != null)
            {
                @Button.started -= m_Wrapper.m_MenuExitActionsCallbackInterface.OnButton;
                @Button.performed -= m_Wrapper.m_MenuExitActionsCallbackInterface.OnButton;
                @Button.canceled -= m_Wrapper.m_MenuExitActionsCallbackInterface.OnButton;
            }
            m_Wrapper.m_MenuExitActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Button.started += instance.OnButton;
                @Button.performed += instance.OnButton;
                @Button.canceled += instance.OnButton;
            }
        }
    }
    public MenuExitActions @MenuExit => new MenuExitActions(this);
    public interface IMenuExitActions
    {
        void OnButton(InputAction.CallbackContext context);
    }
}
